models/alert.py
__author__ = 'Jakub Rachwalski'


# from common.database import Database
from typing import Dict
from dataclasses import dataclass, field, asdict
import uuid
from models.model import Model
from models.item import Item
from models.user import User
from libs.mailgun import Mailgun
from dotenv import load_dotenv
import os


@dataclass(eq=False)
class Alert(Model):
    collection: str = field(init=False, default="alerts")
    item_name: str
    item_id: str
    price_limit: float
    user_email: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)
        self.user = User.get_by_email(self.user_email)

    def json(self) -> Dict:
        return asdict(self)

#    def json(self) -> Dict:
#        return {
#            "_id": self._id,
#            "item_id": self.item_id,
#            "price_limit": self.price_limit,
#        }

    def load_item_price(self) -> float:
        self.item.load_price()
        return self.item.price

    def notify_if_price_reached(self):

        # print(self.item.price)
        # print(self.price_limit)

        if self.item.price < self.price_limit:
            load_dotenv()
            from_email = os.environ.get('FROM_EMAIL', None)

            response = Mailgun.send_mail(
                [f"{from_email}"],
                f"Notification for {self.item_name}",
                f"Price of {self.item_name} has dropped below {self.price_limit}! Latest price: {self.item.price}. Go to this address to check your item: {self.item.url}.",
                f'<p>Price of {self.item_name} has dropped below {self.price_limit}! </p><p>Latest price: {self.item.price}. </p><p>Go to <a href="{self.item.url}">this</a. address to check your item.</p>'
            )
            print(response)

views/alerts.py
__author__ = 'Jakub Rachwalski'

from flask import Blueprint, render_template, request, url_for, redirect, session
from models.alert import Alert
from models.item import Item
from models.store import Store
from models.user import requires_login


alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route("/")
@requires_login
def index():
    # alerts = Alert.all()
    print(session['email'])
    alerts = Alert.find_many_by('user_email', session['email'])
    return render_template('alerts/index.html', alerts=alerts)


@alert_blueprint.route("/new", methods=['GET', 'POST'])
@requires_login
def new_alert():
    if request.method == 'POST':
        # process the data
        item_url = request.form['item_url']
        price_limit = float(request.form['price_limit'])
        item_name = request.form['item_name']
        user_email = session['email']

        store = Store.get_by_url(item_url)
        # print(store)
        item = Item(item_url, store.tag_name, store.query)
        # print(item)
        item.load_price()
        # print(item.load_price())
        item.save_to_mongo()

        Alert(item_name, item._id, price_limit, user_email).save_to_mongo()

        return redirect(url_for('.index'))

    else:

        return render_template('alerts/new_alert.html')


@alert_blueprint.route("/edit/<string:alert_id>", methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):

    alert = Alert.get_by_id(alert_id)

    if request.method == 'POST':
        if alert.user_email == session['email']:
            alert.price_limit = float(request.form['price_limit'])
            alert.save_to_mongo()

            return redirect(url_for('.index'))

    else:
        return render_template('alerts/edit_alert.html', alert=alert)


@alert_blueprint.route("/delete/<string:alert_id>")
@requires_login
def remove_alert(alert_id):

    alert = Alert.get_by_id(alert_id)

    if alert.user_email == session['email']:
        item = Item.get_by_id(alert.item_id)
        item.remove_from_mongo()
        alert.remove_from_mongo()

    return redirect(url_for('.index'))

templates/alerts/edit_alert.html
{% extends "base.html" %}

{% block content %}

    <header><h1>Update Alert</h1></header>
    <section class="update-alert-form">
        <form method = "post">

            <div class="form-group">
                <label for="item_name">Item Name</label>
                <input type="text" class="form-control" id="item_name" name="item_name" value="{{alert.name}}" disabled/>
            </div>

            <div class="form-group">
                <label for="item_url">Item URL</label>
                <input type="text" class="form-control" id="item_url" name="item_url" value="{{alert.item.url}}" disabled/>
            </div>

            <div class="form-group">
                <label for="price_limit">Price Limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="100" value="{{alert.price_limit}}" aria-describedby="tagNameHelp"/>
                <small class="form-text text-muted" id="tagNameHelp">
                    What is the Price Limit
                </small>
            </div>

            <button class="btn btn-primary" type="submit">Update</button>


        </form>


    </section>

{% endblock %}

templates/alerts/index.html
{% extends "base.html" %}

{% block content %}

    <header>
        <h1>Alerts</h1>

    </header>
    <section>
    <div class="list-group mb-3">
        {% for alert in alerts%}
            <div class="list-group-item">
                <h4>{{alert.item_name}}</h4>
                    <p>
                        <a href="{{alert.item.url}}" >{{alert.item_id}} (last price: {{alert.item.price}})</a>

                    </p>

                    <a class="btn btn-secondary" href="{{url_for('alerts.edit_alert', alert_id=alert._id) }}">
                        Edit

                    </a>

                    <a class="btn btn-danger" href="{{url_for('alerts.remove_alert', alert_id=alert._id) }}">
                        Delete

                    </a>

            </div>




        {% endfor %}
    </div>


        <a class="btn btn-primary" href="{{url_for('alerts.new_alert')}}" >
            Create New
        </a>



</section>


{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %}

{% block content %}

    <header><h1>Create Alert</h1></header>
    <section class="create-alert-form">
        <form method = "post">

            <div class="form-group">
                <label for="item_name">Item Name</label>
                <input type="text" class="form-control" id="item_name" name="item_name" placeholder="Item"/>
            </div>

            <div class="form-group">
                <label for="item_url">Item URL</label>
                <input type="text" class="form-control" id="item_url" name="item_url" placeholder="https://allegro.pl/"/>
            </div>

            <div class="form-group">
                <label for="price_limit">Price Limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="100" aria-describedby="tagNameHelp"/>
                <small class="form-text text-muted" id="tagNameHelp">
                    What is the Price Limit
                </small>
            </div>

            <button class="btn btn-primary" type="submit">Submit</button>


        </form>


    </section>

{% endblock %}