models/store.py
__author__ = 'Jakub Rachwalski'

from typing import Dict
import uuid
import re
from models.model import Model
from dataclasses import dataclass, field, asdict


@dataclass(eq=False)
class Store(Model):

    collection: str = field(default="stores", init=False)
    name: str
    url_prefix: str
    tag_name: str
    query: Dict
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def json(self) -> Dict:
        return asdict(self)


#    def json(self) -> Dict:
#
#        jason = {
#            "_id": self._id,
#            "name": self.name,
#            "url_prefix": self.url_prefix,
#            "tag_name": self.tag_name,
#            "query": self.query
#        }
#        # print(jason)
#        return jason

    @classmethod
    def get_by_name(cls, store_name: str) -> 'Store':
        return cls.find_one_by('name', store_name)

    @classmethod
    def get_by_url_prefix(cls, url_prefix: str) -> 'Store':
        url_regex = {"$regex": "^{}".format(url_prefix)}
        return cls.find_one_by('url_prefix', url_regex)

    @classmethod
    def get_by_url(cls, url: str) -> 'Store':
        url_regex = re.compile(r"(https?://.*?/)")
        match = url_regex.search(url)
        url_prefix = match.group(1)
        return cls.get_by_url_prefix(url_prefix)

views/stores.py
__author__ = 'Jakub Rachwalski'

from flask import Blueprint, render_template, request, url_for, redirect
# from models.alert import Alert
# from models.item import Item
from models.user import requires_admin, requires_login
from models.store import Store
import json


store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route("/")
@requires_login
def index():
    stores = Store.all()
    return render_template('stores/index.html', stores=stores)


@store_blueprint.route("/new", methods=['GET', 'POST'])
@requires_admin
def new_store():
    if request.method == 'POST':
        # process the data

        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = request.form['query']
        query = query.replace("\'", "\"")
        query = json.loads(query)

        Store(name, url_prefix, tag_name, query).save_to_mongo()
        return redirect(url_for('.index'))

    else:

        return render_template('stores/new_store.html')


@store_blueprint.route("/edit/<string:store_id>", methods=['GET', 'POST'])
@requires_admin
def edit_store(store_id):

    store = Store.get_by_id(store_id)

    if request.method == 'POST':
        store.name = request.form['name']
        store.url_prefix = request.form['url_prefix']
        store.tag_name = request.form['tag_name']
        query = request.form['query']
        query = query.replace("\'", "\"")
        store.query = json.loads(query)

        store.save_to_mongo()
        return redirect(url_for('.index'))

    else:
        return render_template('stores/edit_store.html', store=store)


@store_blueprint.route("/delete/<string:store_id>")
@requires_admin
def remove_store(store_id):

    store = Store.get_by_id(store_id)
    store.remove_from_mongo()

    return redirect(url_for('.index'))

templates/stores/edit_store.html
{% extends "base.html" %}

{% block content %}

    <header><h1>Create Store</h1></header>
    <section class="edit-store-form">
        <form method = "post">

            <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Allegro.pl" value="{{store.name}}"/>
            </div>

            <div class="form-group">
                <label for="url_prefix">URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://allegro.pl/" value="{{store.url_prefix}}"/>
            </div>

            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="p" value="{{store.tag_name}}" aria-describedby="tagNameHelp"/>
                <small class="form-text text-muted" id="tagNameHelp">
                    What is the Tag
                </small>
            </div>

            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "price"}' value="{{store.query}}" aria-describedby="queryHelp"/>
                <small class="form-text text-muted" id="queryHelp">
                    What is the Query
                </small>
            </div>

            <button class="btn btn-primary" type="submit">Edit</button>


        </form>


    </section>

{% endblock %}

templates/stores/index.html
{% extends "base.html" %}

{% block content %}

    <header>
        <h1>Stores</h1>

    </header>
    <section>
    <div class="list-group mb-3">
        {% for store in stores%}
            <div class="list-group-item">
                <h4>{{store.name}}</h4>
                    <p>
                        <a href="{{store.url_prefix}}" >{{store.url_prefix}}</a>

                    </p>
                    <p>
                        <a >{{store.tag_name}}</a>

                    </p>
                    <p>
                        <a >{{store.query}}</a>

                    </p>


                    {% if session['email'] == config.ADMIN %}

                    <a class="btn btn-secondary" href="{{url_for('stores.edit_store', store_id=store._id) }}">
                        Edit

                    </a>
                    <a class="btn btn-danger" href="{{url_for('stores.remove_store', store_id=store._id) }}">
                        Delete

                    </a>

                    {% endif %}

            </div>




        {% endfor %}
    </div>

        {% if session['email'] == config.ADMIN %}
            <a class="btn btn-primary" href="{{url_for('stores.new_store')}}" >
                Create New
            </a>
        {% endif %}


</section>


{% endblock %}

templates/stores/new_store.html
{% extends "base.html" %}

{% block content %}

    <header><h1>Create Store</h1></header>
    <section class="create-item-form">
        <form method = "post">

            <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Allegro.pl"/>
            </div>

            <div class="form-group">
                <label for="url_prefix">URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://allegro.pl/"/>
            </div>

            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="p" aria-describedby="tagNameHelp"/>
                <small class="form-text text-muted" id="tagNameHelp">
                    What is the Tag
                </small>
            </div>

            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "price"}' aria-describedby="queryHelp"/>
                <small class="form-text text-muted" id="queryHelp">
                    What is the Query
                </small>
            </div>

            <button class="btn btn-primary" type="submit">Submit</button>


        </form>


    </section>

{% endblock %}